---
- name: generate a search_user_secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: search_user_secret
- name: generate a public_user_secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: public_user_secret
- name: generate a staff_user_secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: staff_user_secret
- name: generate a frontend_cookie_secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64"
  register: frontend_cookie_secret
- name: generate a public_cookie_secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64"
  register: public_cookie_secret
