---
# Use --extra-vars "tenant_name=<new tenant name>" to the
#ansible-playbook call to set new tenant name
-   hosts: aspace-cluster
    gather_facts: True         
    vars:
      db_server: 'aspace.crqkpkb4l2po.us-east-1.rds.amazonaws.com'
      db_port: 3306
      db_user: 'rds_aspace_admin'
      dir_code_src: '~/code/'
      dir_servers: '~/servers/'
      dir_aspace_root: '/aspace/'
      url_jdbc_base: "jdbc:mysql://{{ db_server }}:{{ db_port }}/"
      url_jdbc_suffix: '&useUnicode=true&characterEncoding=UTF-8'
    tasks:
    - fail: msg='Need to set tenant name by adding --extra-vars "tenant_name=<new tenant name>" to ansible-playbook call'
      when: tenant_name == None
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }}
    - name: get start port
      shell: cat ~/.port_next_tenant
      register: start_port
    - name: get the db master password
      local_action: shell cat ~/.dbpass
      register: pswd_db_master 
    - fail: msg='No ~/.dbpass file'
      when: pswd_db_master == None
    - name: generate a random password for tenant db user
      shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16"
      register: pswd_db_user 
    - debug: msg="MYSQL PASSWORD FOR {{ tenant_name }} -- {{ pswd_db_user.stdout }}"
    - include: tasks/generate_aspace_secrets.yml
    - name: create tenant user
      command: sudo /usr/sbin/useradd -U {{ tenant_name }}
    - debug: msg="MYSQL PASSWORD FOR {{ tenant_name }} -- {{ pswd_db_user.stdout }}"
    - name: create mysql database
      mysql_db: name={{ tenant_name }} encoding='utf8' login_host={{ db_server }} login_password={{ pswd_db_master.stdout }} login_user={{ db_user }}
    - name: create mysql user {{ tenant_name }} with PASSWORD {{ random_pwd.stdout }}
      mysql_user: login_host={{ db_server }} login_password={{ pswd_db_master.stdout }} login_user={{ db_user }} name={{ tenant_name }} password={{ pswd_db_user.stdout }} host=% priv={{ tenant_name }}.*:ALL
    - name: copy tenant dir template dirs to tenant dir
      shell: "cp -a {{ dir_aspace_root }}/archivesspace/tenants/_template {{ dir_aspace_root}}/archivesspace/tenants/{{ tenant_name }}"
    - name: run init_tenant
      shell: chdir={{ dir_aspace_root }}/archivesspace/tenants/{{ tenant_name }}/archivesspace/  ./init_tenant.sh stable
    - set_fact:
        url_jdbc_aspace: "{{ url_jdbc_base }}{{ tenant_name }}?user={{ tenant_name }}&password={{ pswd_db_user.stdout }}{{ url_jdbc_suffix }}"
    - name: config tenant db access
      template: src=templates/aspace/config.rb.j2 dest={{ dir_aspace_root }}/archivesspace/tenants/{{ tenant_name }}/archivesspace/config/config.rb
    - name: config tenant instance
      template: src=templates/aspace/instance_hostname.rb.j2 dest={{ dir_aspace_root }}/archivesspace/tenants/{{ tenant_name }}/archivesspace/config/instance_{{ ansible_hostname }}.rb mode=755
    - name: setup tenant database
      shell: chdir={{ dir_aspace_root }}/archivesspace/tenants/{{ tenant_name }}/archivesspace/ ./scripts/setup-database.sh

    - name: update starting port for next tenant
      lineinfile: dest=~/.port_next_tenant regexp=(\\d)+ line="{{ start_port.stdout|int + 10 }}" state=present backrefs=yes

    - name: create monit monitor for tenant
      sudo: yes
      template: src=templates/aspace/service.monitrc dest=/etc/monit.d/{{ tenant_name }}-aspace.monitrc
    - name: save tenant information
      lineinfile: dest=~/.tenant_info create=yes line="{{ tenant_name }} - {{ pswd_db_user.stdout }} | front port - {{ start_port.stdout }} | public port - {{ start_port.stdout|int + 1}}"
    - name: save tenant information, master
      delegate_to: 127.0.0.1
      lineinfile: dest=~/.tenant_info create=yes line="{{ tenant_name }} - {{ tenant_db_password }} | host - {{ ansible_hostname}} | front port - {{ start_port.stdout }} | public port - {{ start_port.stdout|int + 1}}"
    - debug: msg="MYSQL PASSWORD FOR {{ tenant_name }} -- {{ pswd_db_user.stdout }}"
    - debug: msg="Hostname-> {{ ansible_hostname }}"
    - debug: msg="Archivespace public  port-> {{ start_port.stdout|int + 1 }}"
    - debug: msg="Archivespace frontend port-> {{ start_port.stdout }}"
    - name: start archivesspace server
      sudo: yes
      shell: /etc/init.d/aspace-cluster start-tenant {{ tenant_name }}
    - name: reload monit
      sudo: yes
      command: monit reload
    - name: reload monit
      sudo: yes
      command: monit reload
    - name: monitor new tenant instance
      sudo: yes
      command: monit monitor {{ tenant_name }}-aspace
