---
# start all aspace servers
-   hosts: aspace-cluster
    gather_facts: True         
    tasks:
    - name: start aspace-cluster
      sudo: yes
      service:
        name: aspace-cluster
        state: started
