---
-   hosts: localhost
    connection: local
    gather_facts: True         
    tasks:
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }}
    - name: make code src directory
      file: path={{ role_home_dir.stdout }}/code/aspace state=directory
    - name: download archivespace.zip
      get_url: url=https://github.com/archivesspace/archivesspace/archive/master.zip dest={{ role_home_dir.stdout }}/code/archivesspace.zip
    - name: unpack archivesspace
      unarchive: src={{ role_home_dir.stdout }}/code/archivesspace.zip dest={{ role_home_dir.stdout }}/code/aspace/
# NEED TO MAKE /aspace to mimic nfs mount?
    - name: Create cluster root dir
      file: path={{ role_home_dir.stdout }}/aspace state=directory
    - name: copy archivesspace files
      synchronize: src={{ role_home_dir.stdout }}/code/aspace/archivesspace-master/clustering/files/ dest={{ role_home_dir.stdout }}/aspace/ recursive=yes
