---
-   hosts: localhost
    connection: local
    gather_facts: True         
    vars:
      dir_code_src: '~/code/'
      dir_servers: '~/servers/'
    tasks:
    - name: get public ip
      shell:  GET http://169.254.169.254/latest/meta-data/public-ipv4
      register: public_ip
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }}
    - name: put bashrc in place, with fix for Amazon certs if necessary
      template: src=./templates/ingest/bashrc.j2 dest=~/.bashrc
    - name: put gitconfig in place
      template: src=./templates/ingest/gitconfig.j2 dest=~/.gitconfig
    - name: make home bin dir
      file: path=~/bin state=directory
    - include: tasks/ingest/monit_setup.yml
    - name: create init.d-monit #NOTE: must use ec2-user to install
      template: src=./templates/solr/init.d-monit.j2 dest=~/init.d-monit
    - name: monit validate
      shell: monit validate
