---
-   hosts: localhost
    connection: local
    gather_facts: True         
    vars:
      dir_code_src: '~/code/'
      dir_servers: '~/servers/'
    tasks:
    - name: get public ip
      shell:  GET http://169.254.169.254/latest/meta-data/public-ipv4
      register: public_ip
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }}
    - name: put bashrc in place, with fix for Amazon certs if necessary
      template: src=./templates/ingest/bashrc.j2 dest=~/.bashrc
    - name: put gitconfig in place
      template: src=./templates/ingest/gitconfig.j2 dest=~/.gitconfig
    - name: make home bin dir
      file: path=~/bin state=directory
    - name: start redis docker
      sudo: yes
      docker: image=tutum/redis command="/run.sh" ports=6379:6379 name=redis
    - name: start couchdb docker
      sudo: yes
      docker: image=mredar/couchdb command="/run.sh" ports=5984:5984 name=couchdb volumes=/var/lib/couchdb
    - name: put akara env list in place
      template: src=./templates/ingest/akara-env.list.j2 dest=/home/ec2-user/.akara-env.list
    - name: start akara docker
      sudo: yes
      comman: /usr/bin/docker run -d -p 8889:8889 --env-file /home/ec2-user/.akara-env.list --name=akara mredar/akara-dpla /run.sh
    - name: Display IP address and port mappings for containers
      debug: msg={{inventory_hostname}}:{{item['HostConfig']['PortBindings']['8080/tcp'][0]['HostPort']}}
      with_items: docker_containers
    - include: tasks/ingest/monit_setup.yml
    - name: monit validate
      sudo: yes
      shell: monit validate
