---
-   hosts: localhost
    connection: local
    gather_facts: True         
    tasks:
    - name: move nginx conf in place
    #sudo: yes
      template: src=templates/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
