---
  - hosts: localhost
    gather_facts: True         
    tasks: 
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }} and hostname.stdout
    - include: tasks/shibboleth.yml app=registry  
    - include: tasks/monit.yml app=registry
    - name: add stunnel monit control file
      template:
        src: templates/registry/stunnel-monitrc
        dest: ~/.monit/stunnel-monitrc
    - name: check out documentation
      git: repo=https://github.com/ucldc/ucldc-docs.git version=mirror dest=~/webroot/ucldc-docs
    - name: mirror the documentation from github (cheap trick)
      command: ./mirror_docs.py chdir=~/webroot/ucldc-docs creates=~/webroot/ucldc-docs/ucldc.github.io
    - name: copy fonts for documentation
      copy: src=~/webroot/ucldc-docs/fonts dest=~/webroot/ucldc-docs/ucldc.github.io/ucldc-docs/vendor/bootstrap-partial
    - name: get the bruin icon
      get_url: url=http://ucldc.github.io/ucldc-docs/images/bruin.png  dest=~/webroot/ucldc-docs/ucldc.github.io/ucldc-docs/images/bruin.png
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
    - name: build avram environment
      command: ~/code/avram/init.sh creates=~/code/avram/bin/activate
    - name: setup db dump cron
      cron: name="dump django db" hour="1" minute="7" job="~/code/avram/dbdump.sh" backup=True
