---
  - hosts: localhost
    gather_facts: True         
    tasks: 
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }} and hostname.stdout
    - include: tasks/shibboleth.yml app=registry  
    - include: tasks/monit.yml app=registry
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
    - name: build avram environment
      command: ~/code/avram/init.sh creates=~/code/avram/bin/activate
    - name: setup db dump cron
      cron: name="dump django db" hour="1" minute="7" job="~/code/avram/dbdump.sh" backup=True
